#!/bin/sh
### BEGIN INIT INFO
# Provides:          display
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start display
# Description:       Start/stop display
### END INIT INFO

DESC="display  service"


do_start()
{
   echo "Starting display"
   /home/pi/raspberry_utils/display.py 2>&1 &
}

case "$1" in
   start)
     do_start
     ;;
   *)
     echo "Usage : display start"
esac

exit 0
